[build]
  base = ""
  publish = "storybook-static"
  command = "corepack enable && pnpm storybook:build"
  environment = { NODE_VERSION = "18.16.0" }

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = false
